class KeyManager {
  static const String id="idKey";
  static const String thisDevice="thisDeviceKey";
  static const String isSent="isSentKey";
  static const String sentDate="sentDateKey";
  static const String listOfSolders="listOfSoldersKey";
  static const String listDeviceAccess="listDeviceAccessKey";
  static const String access="accessKey";
  static const String change="changeKey";
  static const String control="controlKey";
  static const String name = "nameKey";
  static const String forces = "forcesKey";
  static const String militaryId = "militaryIdKey";
  static const String center = "centerKey";
  static const String governorate = "governorateKey";
  static const String address = "addressKey";
  static const String idNumber = "idNumberKey";
  static const String weapon = "weaponKey";
  static const String tripleNumber = "tripleNumberKey";
  static const String educationalLevel = "educationalLevelKey";
  static const String recruitmentArea = "recruitmentAreaKey";
  static const String enlistmentDate = "enlistmentDateKey";
  static const String dateOfBirth = "dateOfBirthKey";
  static const String serviceEndDate = "serviceEndDateKey";
  static const String bloodType = "bloodTypeKey";
  static const String medicalLevel = "medicalLevelKey";
  static const String religion = "religionKey";
  static const String phoneNumber = "phoneNumberKey";
  static const String service = "serviceKey";
  static const String serviceDuration = "serviceDurationKey";
  static const String lostDuration = "lostDurationKey";
  static const String netServiceDuration = "netServiceDurationKey";
  static const String listMilitaryViolation = "listMilitaryViolationKey";

  static const String dateOfTheCrime="dateOfTheCrimeKey";
  static const String description="descriptionKey";
  static const String imposedPunishment="imposedPunishmentKey";
  static const String orderForThePunishment="orderForThePunishmentKey";
}
