// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4TXeOCeFLWvGwWhT4Q_ZaLvLgOIKRw4U',
    appId: '1:542865630319:web:f069ff8d05120dc4bf999a',
    messagingSenderId: '542865630319',
    projectId: 'history-ad477',
    authDomain: 'history-ad477.firebaseapp.com',
    storageBucket: 'history-ad477.appspot.com',
    measurementId: 'G-CH2TMPZ9WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5AfeuiT38lP-onjXOD4yFp_AfDbTl5TA',
    appId: '1:542865630319:android:cf667174db8bb4e3bf999a',
    messagingSenderId: '542865630319',
    projectId: 'history-ad477',
    storageBucket: 'history-ad477.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaonNt_sEcDGYs-o1n7IdhdXQqKv4udN0',
    appId: '1:542865630319:ios:86428ce8aa1168a6bf999a',
    messagingSenderId: '542865630319',
    projectId: 'history-ad477',
    storageBucket: 'history-ad477.appspot.com',
    iosBundleId: 'com.example.solderHistory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaonNt_sEcDGYs-o1n7IdhdXQqKv4udN0',
    appId: '1:542865630319:ios:86428ce8aa1168a6bf999a',
    messagingSenderId: '542865630319',
    projectId: 'history-ad477',
    storageBucket: 'history-ad477.appspot.com',
    iosBundleId: 'com.example.solderHistory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4TXeOCeFLWvGwWhT4Q_ZaLvLgOIKRw4U',
    appId: '1:542865630319:web:31e541198b98708cbf999a',
    messagingSenderId: '542865630319',
    projectId: 'history-ad477',
    authDomain: 'history-ad477.firebaseapp.com',
    storageBucket: 'history-ad477.appspot.com',
    measurementId: 'G-P14LWRDKQ8',
  );
}
